---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-configmap-volume
          - mountPath: /usr/share/nginx/html
            name: nginx-configmap-volume
      volumes:
        - name: nginx-configmap-volume
          configMap:
            name: nginx-configmap

